### ISSUE TITLE
StrongType constructor not accessible from external module

### ISSUE THREAD

**Issue by philco81** [yunjhongwu/strong-type#65]
Hi Yun-Jhong Wu,

Thanks for the crate StrongType, This is a great one.
Sorry if the issue I have is not very well explained, I am a newbie to rust.

I have external file, say **timestamp.rs**, where I define a strong type:
`#[derive(StrongType)]`
`#[strong_type(auto_operators)]`
`pub struct Timestamp(usize);`

When using in the **main.rs** an expression such as: 

`Timestamp(123456789) + Timestamp(987654321)`

I get an error in the **main.rs**:

- _cannot initialize a tuple struct which contains private fields [...]_
- _timestamp.rs(8, 20): constructor is not visible here due to private fields_
- _timestamp.rs(8, 20): consider making the field publicly accessible: `pub`_

If in **timestamp.rs**  I do add `pub` in the declaration, 

`#[derive(StrongType)]`
`#[strong_type(auto_operators)]`
`pub struct NbTeams(pub usize);`

I get another error, in the timestamp.rs:
- _proc-macro derive panicked_
- _message: Strong type must be a tuple struct with one private field._ 

There might be some proper way of doing it, but I am not yet good enough at rust to get it.

Thanks.

**Comment by yunjhongwu** [comment]
Currently we have to construct strongly-typed structs with `new`, e.g. `Timestamp::new(123456789_usize)`. Note that `new` only accepts types that implement `Into<usize>`. This approach is somewhat safer although probably not very visually appealing.

In earlier versions, I attempted to support `pub` but encountered issues that I wasn't able to resolve. I will try to implement it again.

**Comment by yunjhongwu** [comment]
It seems I can enable this by removing the visibility check. I'll test this further over the weekend, and if there are no issues, I'll release a new version. Meanwhile you can try this by adding `strong-type = { git = "https://github.com/yunjhongwu/strong-type", branch = "allow-pub" }` to your `Cargo.toml`.

**Comment by philco81** [comment]
Thanks a lot.  I'm looking forward to tryong it. I'll give you my feedback.

**Comment by yunjhongwu** [comment]
`v0.11.0` released. Thanks for the feedback!
